### ISSUE TITLE
Use yarn in CONTRIBUTING.md

### ISSUE THREAD

**Issue by ollelauribostrom** [ollelauribostrom/hindex#1]
The CONTRIBUTING.md currently states that npm should be used. As stated in the README, this project is now using yarn so this should be updated.

- Use `yarn test` instead of `npm test`/`npm run test`
- Use `yarn lint` instead of `npm run lint`

**Comment by clrxbl** [comment]
#2

**Comment by ollelauribostrom** [comment]
Thank you for the patch!
